### ISSUE TITLE
How is this installed?

### ISSUE THREAD

**Issue by gkrawiec** [MalayaliRobz/Program-B#2]
Please improve the installation instructions. I came here from product hunt. A link to github with no installer is not very friendly.

**Comment by MrRobz** [comment]
Have added a downloadable asset zip in release page:
https://github.com/MrRobz/menubar-auto-brightness/releases

Menubar.Auto.Brightness-darwin-x64-1.0.0-beta.zip

Once extracted, double click Menubar Auto Brightness.app on your mac. It will ask for some permissions based on your macOS version. Go to settings -> security& privacy and give all relevant permissions. Now restart the app and stuff should start working hopefully.

Do note this is a beta release, so bugs may arise.
